name: Build and Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust
        run: rustup toolchain install nightly
      - name: Build and test
        run: cargo build -p my_rust_project --verbose
      - name: Success
        run: echo 'Build and test successful'
